# Configuration for classes of static volumes.
classes:
  # the name of local storage class
  - name: local-storage
    # path to the directory of local volumes (discovery directory)
    hostDir: /mnt/disks
    # the mount path of host directory in provisioner pod
    mountDir: /mnt/disks
    volumeMode: Filesystem
    namePattern: "*"
    allowedTopologies:
    blockCleanerCommand:
      - "/scripts/shred.sh"
      - "2"