# PostgreSQL StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql-db
spec:
  serviceName: postgresql-db-service
  selector:
    matchLabels:
      app: postgresql-db
  replicas: 1
  template:
    metadata:
      labels:
        app: postgresql-db
    spec:
      containers:
        - name: postgresql-db
          # image: us-east1-docker.pkg.dev/budget-server-370523/docker-smithers/smithers-psql:1.7
          image: registry.smithers.private/smithers-psql:1.0
          volumeMounts:
          - name: postgresql-db-disk
            mountPath: /data
          resources:
            limits:
              cpu: "250m"
              memory: "200Mi"
            requests:
              cpu: "250m"
              memory: "200Mi"
  volumeClaimTemplates:
  - metadata:
      name: postgresql-db-disk
    spec:
      # storageClassName: pd-standard
      storageClassName: local-storage
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          # storage: 15Gi
          storage: 260Gi