apiVersion: v1
kind: Service
metadata:
  name: smithers-web-service
  labels:
    app: smithers-web
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: smithers-web