apiVersion: apps/v1
kind: Deployment
metadata:
  name: smithers-server-deployment
  labels:
    app: smithers-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smithers-server
  template:
    metadata:
      labels:
        app: smithers-server
    spec:
      containers:
      - name: smithers-server
        image: us-east1-docker.pkg.dev/budget-server-370523/docker-smithers/smithers-server:1.1
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "125m"
            memory: "125Mi"
          requests:
            cpu: "125m"
            memory: "125Mi"
