apiVersion: batch/v1
kind: CronJob
metadata:
  name: smithers-crawler-cron
spec:
  schedule: "0 7 * * *"
  timeZone: "America/Toronto"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: smithers-crawler-pod
            image: registry.smithers.private/smithers-crawler:1.8
            # image: us-east1-docker.pkg.dev/budget-server-370523/docker-smithers/smithers-crawler:1.8
            imagePullPolicy: IfNotPresent
            env:
              - name: DATABASE_CONNECTION_STRING
                valueFrom:
                  secretKeyRef:
                    name: production-psql
                    key: production-psql
            resources:
              limits:
                cpu: "50m"
                memory: "150Mi"
              requests:
                cpu: "50m"
                memory: "150Mi"
          restartPolicy: OnFailure