apiVersion: batch/v1
kind: CronJob
metadata:
  name: smithers-crawler-cron
spec:
  schedule: "0 7 * * *"
  timeZone: "America/Toronto"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: smithers-crawler-pod
            image: us-east1-docker.pkg.dev/budget-server-370523/docker-smithers/smithers-crawler:1.2
            imagePullPolicy: IfNotPresent
            resources:
              limits:
                cpu: "50m"
                memory: "100Mi"
              requests:
                cpu: "50m"
                memory: "100Mi"
          restartPolicy: OnFailure