apiVersion: v1
kind: Service
metadata:
  name: smithers-server-service
  labels:
    app: smithers-server
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: smithers-server